<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../XML-XSL-DTD/test.xsl"?>

<!DOCTYPE library [
	<!ELEMENT library (book+)>
	<!ELEMENT book (Title, Genre, Summary, Pages, ISBN, Author, Price)>
	<!ELEMENT Title (#PCDATA)>
	<!ELEMENT Summary (#PCDATA)>
	<!ELEMENT Pages (#PCDATA)>
	<!ELEMENT ISBN (#PCDATA)>
	<!ELEMENT Author (#PCDATA)>
	<!ELEMENT Price (#PCDATA)>
]>

<library>
	<book category="horror">
		<Title> My Heart is a Chainsaw </Title>
		<Genre> Horror </Genre>
		<Summary> Jade Daniels is an angry, half-Indian outcast with an abusive father, an absent mother, and an entire town that
				wants nothing to do with her. She lives in her own world, a world in which protection comes from an unusual
				source: horror movies…especially the ones where a masked killer seeks revenge on a world that wronged them. And
				Jade narrates the quirky history of Proofrock as if it is one of those movies. But when blood actually starts
				to spill into the waters of Indian Lake, she pulls us into her dizzying, encyclopedic mind of blood and masked
				murderers, and predicts exactly how the plot will unfold. Yet, even as Jade drags us into her dark fever dream,
				a surprising and intimate portrait emerges… a portrait of the scared and traumatized little girl beneath the
				Jason Voorhees mask: angry, yes, but also a girl who easily cries, fiercely loves, and desperately wants a
				home. A girl whose feelings are too big for her body. </Summary>
		<Pages> 432 </Pages>
		<ISBN> 9781982137649 </ISBN>
		<Author> Stephen Graham Jones </Author>
		<Price> 66.07 AED </Price>
	</book>
	
	<book category="novel">
		<Title> Black Sheep </Title>
		<Genre> Horror </Genre>
		<Summary> Nobody has a “normal” family, but Vesper Wright’s is truly…something else. Vesper left home at eighteen and
				never looked back—mostly because she was told that leaving the staunchly religious community she grew up in
				meant she couldn’t return. But then an envelope arrives on her doorstep. Inside is an invitation to the wedding
				of Vesper’s beloved cousin Rosie. It’s to be hosted at the family farm. Have they made an exception to the
				rule? It wouldn’t be the first time Vesper’s been given special treatment. Is the invite a sweet gesture? An
				olive branch? A trap? Doesn’t matter. Something inside her insists she go to the wedding. Even if it means
				returning to the toxic environment she escaped. Even if it means reuniting with her mother, Constance, a former
				horror film star and forever ice queen. When Vesper’s homecoming exhumes a terrifying secret, she’s forced to
				reckon with her family’s beliefs and her own crisis of faith in this deliciously sinister novel that explores
				the way family ties can bind us as we struggle to find our place in the world. </Summary>
		<Pages> 304 </Pages>
		<ISBN> 9780593545850 </ISBN>
		<Author> Rachel Harrison </Author>
		<Price> 75.48 AED </Price>
	</book>

	<book category="horror">
		<Title> Episode Thirteen </Title>
		<Genre> Horror </Genre>
		<Summary> Fade to Black is the newest hit ghost hunting reality TV show. Led by husband and wife team Matt and Claire
				Kirklin, it delivers weekly hauntings investigated by a dedicated team of ghost hunting experts. Episode Thirteen
				takes them to every ghost hunter's holy grail: the Paranormal Research Foundation. This brooding, derelict mansion
				holds secrets and clues about bizarre experiments that took place there in the 1970s. It's also famously haunted,
				and the team hopes their scientific techniques and high tech gear will prove it. But as the house begins to reveal
				itself to them, proof of an afterlife might not be everything Matt dreamed of. A story told in broken pieces, in
				tapes, journals, and correspondence, this is the story of Episode Thirteen -- and how everything went terribly,
				horribly wrong. </Summary>
		<Pages> 464 </Pages>
		<ISBN> 9780316443104 </ISBN>
		<Author> Craig DiLouie </Author>
		<Price> 80.00 AED </Price>
	</book>
</library>
